# Select image from https://hub.docker.com/_/php/
image: tapakan/basetest:latest

stages:
  - test

cache:
  key: "$CI_BUILD_NAME"
  paths:
    - vendor

before_script:
# Install all project dependencies
- composer install
# Run webserver
- php -S localhost:8080 --docroot src > /dev/null 2>&1

# Test
test:
  script:
    - php vendor/bin/codecept run unit -v --no-colors --coverage-text
  artifacts:
    when: always
    expire_in: 2 days
    paths:
      - tests/_output
