# Select image from https://hub.docker.com/_/php/
image: tapakan/basetest:latest

# Select what we should cache
cache:
  paths:
  - vendor/

before_script:
# Install git and unzip (composer will need them)
- apt-get update
# Install all project dependencies
- composer install
# Run webserver
- php -S localhost:8085 --docroot src &>/dev/null&

# Test
test:
  script:
  - php vendor/bin/codecept run -v --no-colors --coverage-text